version: '2'
services:
  jumpserver:
    build: .
    container_name: jumpserver
    restart: always
    ports:
      - "8888:80"
      - "2222:22"
    # environment:
    #   - ENGINE=mysql
    #   - MYSQL_HOST=192.168.64.5
    #   - MYSQL_PORT=3306
    #   - MYSQL_USER=root
    #   - MYSQL_PASS=love1314
    #   - MYSQL_NAME=jumpserver
    #   - MAIL_ENABLED=false
